USE [SanwaSDB]
GO
/****** Object:  Table [dbo].[TM仕入日付]    Script Date: 2025/04/18 17:09:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TM仕入日付](
	[id] [int] NOT NULL,
	[仕入日付] [date] NOT NULL,
	[初期登録日] [datetime] NULL,
	[登録変更日] [datetime] NULL,
 CONSTRAINT [PK_TM仕入日付] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

