'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Y_DisplayName() As String
            Get
                Return CType(Me("Y_DisplayName"),String)
            End Get
            Set
                Me("Y_DisplayName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Y_Enabled() As Boolean
            Get
                Return CType(Me("Y_Enabled"),Boolean)
            End Get
            Set
                Me("Y_Enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Y_Locked() As Boolean
            Get
                Return CType(Me("Y_Locked"),Boolean)
            End Get
            Set
                Me("Y_Locked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property Y_MaxLength() As Integer
            Get
                Return CType(Me("Y_MaxLength"),Integer)
            End Get
            Set
                Me("Y_MaxLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WindowText")>  _
        Public Property Y_ForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("Y_ForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Y_ForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property Y_BackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("Y_BackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Y_BackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Y_Font() As Global.System.Drawing.Font
            Get
                Return CType(Me("Y_Font"),Global.System.Drawing.Font)
            End Get
            Set
                Me("Y_Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property Y_FocusBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("Y_FocusBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Y_FocusBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Y_CanNextSetFocus() As Boolean
            Get
                Return CType(Me("Y_CanNextSetFocus"),Boolean)
            End Get
            Set
                Me("Y_CanNextSetFocus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Y_CanForwardSetFocus() As Boolean
            Get
                Return CType(Me("Y_CanForwardSetFocus"),Boolean)
            End Get
            Set
                Me("Y_CanForwardSetFocus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Y_SelectText() As Boolean
            Get
                Return CType(Me("Y_SelectText"),Boolean)
            End Get
            Set
                Me("Y_SelectText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Y_EditMode() As Boolean
            Get
                Return CType(Me("Y_EditMode"),Boolean)
            End Get
            Set
                Me("Y_EditMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Y_Alignment() As Integer
            Get
                Return CType(Me("Y_Alignment"),Integer)
            End Get
            Set
                Me("Y_Alignment") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Y_Appearance() As Integer
            Get
                Return CType(Me("Y_Appearance"),Integer)
            End Get
            Set
                Me("Y_Appearance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Y_BorderStyle() As Integer
            Get
                Return CType(Me("Y_BorderStyle"),Integer)
            End Get
            Set
                Me("Y_BorderStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Y_OldValue() As String
            Get
                Return CType(Me("Y_OldValue"),String)
            End Get
            Set
                Me("Y_OldValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property M_DisplayName() As String
            Get
                Return CType(Me("M_DisplayName"),String)
            End Get
            Set
                Me("M_DisplayName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property M_Enabled() As Boolean
            Get
                Return CType(Me("M_Enabled"),Boolean)
            End Get
            Set
                Me("M_Enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property M_Locked() As Boolean
            Get
                Return CType(Me("M_Locked"),Boolean)
            End Get
            Set
                Me("M_Locked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property M_MaxLength() As Integer
            Get
                Return CType(Me("M_MaxLength"),Integer)
            End Get
            Set
                Me("M_MaxLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WindowText")>  _
        Public Property M_ForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("M_ForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("M_ForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property M_BackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("M_BackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("M_BackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property M_Font() As Global.System.Drawing.Font
            Get
                Return CType(Me("M_Font"),Global.System.Drawing.Font)
            End Get
            Set
                Me("M_Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property M_FocusBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("M_FocusBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("M_FocusBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property M_CanNextSetFocus() As Boolean
            Get
                Return CType(Me("M_CanNextSetFocus"),Boolean)
            End Get
            Set
                Me("M_CanNextSetFocus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property M_CanForwardSetFocus() As Boolean
            Get
                Return CType(Me("M_CanForwardSetFocus"),Boolean)
            End Get
            Set
                Me("M_CanForwardSetFocus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property M_SelectText() As Boolean
            Get
                Return CType(Me("M_SelectText"),Boolean)
            End Get
            Set
                Me("M_SelectText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property M_EditMode() As Boolean
            Get
                Return CType(Me("M_EditMode"),Boolean)
            End Get
            Set
                Me("M_EditMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property M_Alignment() As Integer
            Get
                Return CType(Me("M_Alignment"),Integer)
            End Get
            Set
                Me("M_Alignment") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property M_Appearance() As Integer
            Get
                Return CType(Me("M_Appearance"),Integer)
            End Get
            Set
                Me("M_Appearance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property M_BorderStyle() As Integer
            Get
                Return CType(Me("M_BorderStyle"),Integer)
            End Get
            Set
                Me("M_BorderStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property M_OldValue() As String
            Get
                Return CType(Me("M_OldValue"),String)
            End Get
            Set
                Me("M_OldValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property D_DisplayName() As String
            Get
                Return CType(Me("D_DisplayName"),String)
            End Get
            Set
                Me("D_DisplayName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property D_Enabled() As Boolean
            Get
                Return CType(Me("D_Enabled"),Boolean)
            End Get
            Set
                Me("D_Enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property D_Locked() As Boolean
            Get
                Return CType(Me("D_Locked"),Boolean)
            End Get
            Set
                Me("D_Locked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property D_MaxLength() As Integer
            Get
                Return CType(Me("D_MaxLength"),Integer)
            End Get
            Set
                Me("D_MaxLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WindowText")>  _
        Public Property D_ForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("D_ForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("D_ForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property D_BackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("D_BackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("D_BackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property D_Font() As Global.System.Drawing.Font
            Get
                Return CType(Me("D_Font"),Global.System.Drawing.Font)
            End Get
            Set
                Me("D_Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property D_FocusBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("D_FocusBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("D_FocusBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property D_CanNextSetFocus() As Boolean
            Get
                Return CType(Me("D_CanNextSetFocus"),Boolean)
            End Get
            Set
                Me("D_CanNextSetFocus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property D_CanForwardSetFocus() As Boolean
            Get
                Return CType(Me("D_CanForwardSetFocus"),Boolean)
            End Get
            Set
                Me("D_CanForwardSetFocus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property D_SelectText() As Boolean
            Get
                Return CType(Me("D_SelectText"),Boolean)
            End Get
            Set
                Me("D_SelectText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property D_EditMode() As Boolean
            Get
                Return CType(Me("D_EditMode"),Boolean)
            End Get
            Set
                Me("D_EditMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property D_Alignment() As Integer
            Get
                Return CType(Me("D_Alignment"),Integer)
            End Get
            Set
                Me("D_Alignment") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property D_Appearance() As Integer
            Get
                Return CType(Me("D_Appearance"),Integer)
            End Get
            Set
                Me("D_Appearance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property D_BorderStyle() As Integer
            Get
                Return CType(Me("D_BorderStyle"),Integer)
            End Get
            Set
                Me("D_BorderStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property D_OldValue() As String
            Get
                Return CType(Me("D_OldValue"),String)
            End Get
            Set
                Me("D_OldValue") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ExDateText.My.MySettings
            Get
                Return Global.ExDateText.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
