USE [SanwaSDB]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IX_TM棚番_製品_仕様] ON [dbo].[TM棚番]
(
	[製品NO] ASC,
	[仕様NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


CREATE CLUSTERED INDEX [IX_TM棚番_棚番名] ON [dbo].[TM棚番]
(
	[棚番名] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

