'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("e66695678fd2e310b17a79a86632f841a83a97f4c95d39774921a839ef1d36dd184715250c60a5489"& _ 
            "7f42f875a4967afb49b77dc24a69fb3ee4d7fde7db210ce")>  _
        Public Property PleasanterApiKey() As String
            Get
                Return CType(Me("PleasanterApiKey"),String)
            End Get
            Set
                Me("PleasanterApiKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.10.54/api/items/")>  _
        Public Property PleasanterApiUrl() As String
            Get
                Return CType(Me("PleasanterApiUrl"),String)
            End Get
            Set
                Me("PleasanterApiUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.10.54/items/")>  _
        Public Property PleasanterURL() As String
            Get
                Return CType(Me("PleasanterURL"),String)
            End Get
            Set
                Me("PleasanterURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ADODB")>  _
        Public Property AdodbProviderName() As String
            Get
                Return CType(Me("AdodbProviderName"),String)
            End Get
            Set
                Me("AdodbProviderName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=192.168.10.54;Database=SanwaSDB_241016;User ID=sa;P"& _ 
            "assword=1qaz!QAZ")>  _
        Public Property AdodbConnectionString() As String
            Get
                Return CType(Me("AdodbConnectionString"),String)
            End Get
            Set
                Me("AdodbConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.54;Initial Catalog=SanwaSDB_241016;User ID=sa;Password=1qa"& _ 
            "z!QAZ")>  _
        Public Property SqlClientConnectionString() As String
            Get
                Return CType(Me("SqlClientConnectionString"),String)
            End Get
            Set
                Me("SqlClientConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841999")>  _
        Public Property SiteId_TD物件情報() As String
            Get
                Return CType(Me("SiteId_TD物件情報"),String)
            End Get
            Set
                Me("SiteId_TD物件情報") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841987")>  _
        Public Property SiteId_TM得意先() As String
            Get
                Return CType(Me("SiteId_TM得意先"),String)
            End Get
            Set
                Me("SiteId_TM得意先") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841990")>  _
        Public Property SiteId_TM納入先() As String
            Get
                Return CType(Me("SiteId_TM納入先"),String)
            End Get
            Set
                Me("SiteId_TM納入先") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841977")>  _
        Public Property SiteId_TM仕入先() As String
            Get
                Return CType(Me("SiteId_TM仕入先"),String)
            End Get
            Set
                Me("SiteId_TM仕入先") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841983")>  _
        Public Property SiteId_TM配送先() As String
            Get
                Return CType(Me("SiteId_TM配送先"),String)
            End Get
            Set
                Me("SiteId_TM配送先") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841979")>  _
        Public Property SiteId_TM担当者() As String
            Get
                Return CType(Me("SiteId_TM担当者"),String)
            End Get
            Set
                Me("SiteId_TM担当者") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841994")>  _
        Public Property SiteId_TM工事担当() As String
            Get
                Return CType(Me("SiteId_TM工事担当"),String)
            End Get
            Set
                Me("SiteId_TM工事担当") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841992")>  _
        Public Property SiteId_TM製品() As String
            Get
                Return CType(Me("SiteId_TM製品"),String)
            End Get
            Set
                Me("SiteId_TM製品") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841997")>  _
        Public Property SiteId_TMウエルシア物件区分() As String
            Get
                Return CType(Me("SiteId_TMウエルシア物件区分"),String)
            End Get
            Set
                Me("SiteId_TMウエルシア物件区分") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1841984")>  _
        Public Property SiteId_TMウエルシア物件内容() As String
            Get
                Return CType(Me("SiteId_TMウエルシア物件内容"),String)
            End Get
            Set
                Me("SiteId_TMウエルシア物件内容") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SnwMT01.My.MySettings
            Get
                Return Global.SnwMT01.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
